### ISSUE TITLE
Chapter 1: Write a draft of the Introduction

### ISSUE THREAD

**Issue by goncalomcorreia** [goncalomcorreia/phd-thesis-goncalomcorreia#1]
## 📝 Description

In the Introduction, there should be a prelude setting the stage for the thesis. It should aim to put into context and explain, in a high-level way, the title of the thesis.

### Motivation, Objectives, and Scope

In this section, we should describe the point of the thesis - what issues does it aim to solve? Why are the solutions presented important to the scientific community? What open problems were there before the contributions made with this thesis? Put published papers into perspective.

Possible inspiration: Schlichtkrull Thesis.

### Contributions and Thesis Statement

This section will list all contributions made during the thesis. A bullet point for each paper, each bullet point describing the main contributions of each paper. Furthermore, it should have a paragraph describing the thesis as a whole, the main claim it aims to share with the community.

Possible inspiration: Martins Thesis.

### Publications

This section is a simple list of publications made during the PhD.

### Roadmap

In this section, explain what will be described in each Chapter.

## ☑️ Tasks
- [x] Write draft of prelude
- [x] Write draft of Motivation, Objectives, and Scope
- [x] Write draft of Contributions and Thesis Statement
- [x] Write draft of Publications
- [x] Write draft of Roadmap
