### ISSUE TITLE
Chapter 2: Write a draft of the Background

### ISSUE THREAD

**Issue by goncalomcorreia** [goncalomcorreia/phd-thesis-goncalomcorreia#10]
## 📝 Description

This chapter should be one of the last ones to be written. At the moment, we think it should: (1) touch upon the use of neural networks in NLP, particularly seq2seq models, Transformers, and large pre-trained language models; (2) have a section on "Sparsity and Structured Sparsity in Probability Distributions", where sparsemax, entmax, and SparseMAP are introduced and explained; and (3) have a final section about latent variables, particularly discrete and structured ones.

It could be useful to point to relevant literature reviews in each of these sections.

## ☑️ Tasks
- [x] Identify what is the background needed in the context of this thesis regarding neural networks in NLP
- [x] Identify what is the background needed in the context of this thesis regarding Sparsity and Structured Sparsity in Probability Distributions
- [x] Identify what is the background needed in the context of this thesis regarding Latent Variable Models
