### ISSUE TITLE
Chapter 3: Rewrite Motivation and Previous Work, and Final Remarks and Chapter Summary

### ISSUE THREAD

**Issue by goncalomcorreia** [goncalomcorreia/phd-thesis-goncalomcorreia#2]
## 📝 Description

A prelude to the chapter should be written to identify this work in the scope of the thesis.

Inspiration: Niculae thesis.

### Motivation and Previous Work

Rewrite the introduction and related work such that it makes sense in the context of the thesis and the context of the community at the time.

Inspiration: Martins thesis.

### Final Remarks and Chapter Summary

Rewrite the conclusions such that it is aligned with the motivations of the thesis and the motivation described in the Motivation and Previous Work.

Inspiration: Niculae thesis.

## ☑️ Tasks
- [x] Write draft of prelude
- [x] Rewrite Introduction and Related Work to create Motivation and Previous Work
- [x] Rewrite Conclusions to create Final Remarks and Chapter Summary
