### ISSUE TITLE
Feedback: Vlad's feedback on Chapter 1,3,4,5,6 and Abstract

### ISSUE THREAD

**Issue by goncalomcorreia** [goncalomcorreia/phd-thesis-goncalomcorreia#26]
## 📝 Description
Act on the feedback given by Vlad.

## ☑️ Tasks
- [x] make changes in the abstract
- [x] make changes in Chapter 1
- [x] make changes in Chapter 3
- [x] make changes in Chapter 4
- [x] make changes in Chapter 5
- [x] make changes in Chapter 6

## Attachments
[abstract_chapter_1.pdf](https://github.com/goncalomcorreia/phd-thesis-goncalomcorreia/files/8618808/phd-thesis-1.pdf)
[chapter_3_to_6.pdf](https://github.com/goncalomcorreia/phd-thesis-goncalomcorreia/files/8618810/chapter_3_to_6.pdf)
