### ISSUE TITLE
Chapter 6: Make Future Work better

### ISSUE THREAD

**Issue by goncalomcorreia** [goncalomcorreia/phd-thesis-goncalomcorreia#27]
## 📝 Description
Future Work needs to be more descriptive and some stuff could be added.

## ☑️ Tasks
- [x] Add draft editing idea
- [x] Connect future work ideas to thesis theme. Draft editing is transparency and compactness. Semi supervision is data efficiency, etc.
- [x] Look at André's feedback again and act upon it
- [x] Write a broader impact section. Check other papers with broader impact for inspiration (particularly for transformers, pre-trained models, and transparency)
