### ISSUE TITLE
Thesis as a whole: Formatting and edits

### ISSUE THREAD

**Issue by goncalomcorreia** [goncalomcorreia/phd-thesis-goncalomcorreia#28]
## 📝 Description
The thesis needs to be checked as a whole to see if it makes sense as a continuous work.

## ☑️ Tasks
- [x] Check what to turn into a definition box
- [x] switch the colours of definitions and lemmas
- [x] check for grammar errors
- [x] go through all elements of the bibliography and make them pretty
- [x] go through all "TODO" notes in the tex
- [x] read through the whole thing and do any necessary edits
- [x] make notation the same throughout the whole thesis
