### ISSUE TITLE
Chapter 3: Research and Write a draft about Subsequent Work

### ISSUE THREAD

**Issue by goncalomcorreia** [goncalomcorreia/phd-thesis-goncalomcorreia#5]
## 📝 Description
A section of this chapter will be dedicated to research papers that cited the current chapter's paper. We'll need to go over all the papers that cite this chapter's paper, decide which ones to mention, and write a section about them where we highlight the connections.

Inspiration: Schlichtkrull thesis.

## ☑️ Tasks
- [x] Go over all citations in Google Scholar
- [x] Annotate here which works are inspired by this chapter (in a comment)
- [x] Write a summary of each
- [x] Connect everything by writing Subsequent Work section

**Comment by goncalomcorreia** [comment]
List of papers to possibly mention in this subsection:

- https://arxiv.org/abs/2105.14809 (ACL 2021)
- https://aclanthology.org/2020.lrec-1.668/ (LREC 2020)
- https://arxiv.org/abs/2009.14395 (EMNLP 2020)
- https://aclanthology.org/2020.coling-main.399/ (COLING 2020)
- https://arxiv.org/abs/2004.14120 (EAMT 2020)
- https://aclanthology.org/2020.wmt-1.82.pdf (WMT 2020)
- https://aclanthology.org/2020.wmt-1.84.pdf (WMT 2020)
