### ISSUE TITLE
Chapter 5: Research and Write a draft about Subsequent Work

### ISSUE THREAD

**Issue by goncalomcorreia** [goncalomcorreia/phd-thesis-goncalomcorreia#7]
## 📝 Description
A section of this chapter will be dedicated to research papers that cited the current chapter's paper. We'll need to go over all the papers that cite this chapter's paper, decide which ones to mention, and write a section about them where we highlight the connections.

Inspiration: Schlichtkrull thesis.

## ☑️ Tasks
- [x] Go over all citations in Google Scholar
- [x] Annotate here which works are inspired by this chapter (in a comment)
- [x] Write a summary of each
- [x] Connect everything by writing Subsequent Work section

**Comment by goncalomcorreia** [comment]
- https://arxiv.org/abs/2104.05819 (NAACL 2021)
- https://proceedings.neurips.cc/paper/2021/hash/7a430339c10c642c4b2251756fd1b484-Abstract.html (NeurIPS 2021)
- https://proceedings.neurips.cc/paper/2021/hash/47951a40efc0d2f7da8ff1ecbfde80f4-Abstract.html (NeurIPS 2021)
- https://proceedings.neurips.cc/paper/2021/hash/60243f9b1ac2dba11ff8131c8f4431e0-Abstract.html (NeurIPS 2021)
- https://arxiv.org/abs/2112.03638 (arxiv 2021)
- https://arxiv.org/abs/2108.02658 (ICLR 2022)
