### ISSUE TITLE
Chapter 6: Write a draft of the section about "Directions of Future Research"

### ISSUE THREAD

**Issue by goncalomcorreia** [goncalomcorreia/phd-thesis-goncalomcorreia#9]
## 📝 Description

In this section, we aim to share with the community exciting ideas that could stem from the work contributed during this thesis. In particular, we want to highlight ideas that connect the usefulness of discrete and structured latent variables to be applied to NLP and how our method proposed in Chapter 5 can help to achieve better models.

## ☑️ Tasks
- [x] Write a draft of a subsection about applying semi-supervision of latent discrete variables to NLP applications and its possible connections to few-shot learning
- [x] Write a draft of a subsection about the possibility of having a non-differentiable reward signal by priming a pre-trained black-box model with a discrete latent variable
- [x] Write a draft of a subsection about how our sparse enumeration method can be helpful for future work using structured latent variables in NLP
